# Generated by Django 5.1.15 on 2026-06-22 13:13

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('surface_m2', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumise'), ('delimiting', 'En délimitation (géomètre)'), ('verifying', 'En vérification (notaire/cadastre)'), ('validated', 'Validée'), ('rejected', 'Rejetée'), ('disputed', 'En litige')], default='submitted', max_length=20)),
                ('reliability', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Élevée')], default='low', max_length=10)),
                ('name_owner_public', models.BooleanField(default=False, help_text='Le propriétaire consent à afficher son nom publiquement')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parcelles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('title', 'Titre foncier'), ('deed', 'Acte de vente'), ('plan', 'Plan / bornage'), ('id', "Pièce d'identité"), ('other', 'Autre')], max_length=20)),
                ('file', models.FileField(upload_to='documents/')),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='parcelles.parcelle')),
            ],
        ),
        migrations.CreateModel(
            name='Delimitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('surveyor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delimitations', to=settings.AUTH_USER_MODEL)),
                ('parcelle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delimitation', to='parcelles.parcelle')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationDossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Rejetée'), ('more_info', 'Complément demandé')], default='pending', max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verifications', to=settings.AUTH_USER_MODEL)),
                ('parcelle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='parcelles.parcelle')),
            ],
        ),
        migrations.AddIndex(
            model_name='parcelle',
            index=models.Index(fields=['geometry'], name='parcelles_p_geometr_4d1749_idx'),
        ),
    ]
