# Generated by Django 5.1.15 on 2026-07-05 20:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delimitation',
            name='boundary_points',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delimitation',
            name='source_epsg',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delimitation',
            name='validated_geometry',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
