# Generated by Django 5.1.15 on 2026-07-15 09:50

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcelles', '0002_delimitation_boundary_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelle',
            name='declared_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='parcelle',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
