# Generated by Django 5.1.15 on 2026-07-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelles', '0003_parcelle_declared_location_alter_parcelle_geometry'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelle',
            name='reference',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='parcelle',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
