# Generated by Django 5.1.15 on 2026-07-16 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelles', '0004_parcelle_reference_alter_parcelle_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conflit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overlap_area_m2', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('parcelle_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflits_a', to='parcelles.parcelle')),
                ('parcelle_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflits_b', to='parcelles.parcelle')),
            ],
        ),
    ]
