# Generated by Django 5.1.15 on 2026-07-18 19:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelles', '0006_signalement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminBoundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('country_code', models.CharField(db_index=True, max_length=2)),
                ('region_code', models.CharField(blank=True, default='', max_length=10)),
                ('level', models.PositiveSmallIntegerField(default=0)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name': 'Limite administrative',
                'verbose_name_plural': 'Limites administratives',
            },
        ),
    ]
