# Generated by Django 5.1.15 on 2026-07-20 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelles', '0007_adminboundary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('parcelle_declaree', 'Parcelle déclarée'), ('document_ajoute', 'Document ajouté'), ('document_supprime', 'Document supprimé'), ('trace_valide', 'Tracé validé par le géomètre'), ('verification', 'Décision de vérification'), ('statut_change', 'Changement de statut'), ('litige_ouvert', 'Litige ouvert'), ('litige_resolu', 'Litige résolu'), ('signalement', 'Signalement déposé')], db_index=True, max_length=32)),
                ('actor_label', models.CharField(blank=True, max_length=150)),
                ('parcelle_ref', models.CharField(blank=True, max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('prev_hash', models.CharField(blank=True, max_length=64)),
                ('entry_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
                ('parcelle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to='parcelles.parcelle')),
            ],
            options={
                'verbose_name': "Entrée d'audit",
                'verbose_name_plural': "Journal d'audit",
                'ordering': ['-created_at'],
            },
        ),
    ]
