# Generated by Django 5.1.15 on 2026-07-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelles', '0008_auditlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signalement',
            options={'ordering': ['-created_at'], 'verbose_name': 'Demande / signalement', 'verbose_name_plural': 'Demandes & signalements'},
        ),
        migrations.AddField(
            model_name='signalement',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='signalement',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='signalement',
            name='type_demande',
            field=models.CharField(choices=[('info', "Demande d'information"), ('signalement', 'Signalement')], db_index=True, default='signalement', max_length=20),
        ),
        migrations.AlterField(
            model_name='signalement',
            name='motif',
            field=models.CharField(choices=[('renseignement', 'Renseignement sur la parcelle'), ('achat', "Intérêt d'achat ou de location"), ('double_vente', 'Double vente / usurpation'), ('faux_document', 'Faux document'), ('limites', 'Limites contestées'), ('autre', 'Autre')], default='autre', max_length=20),
        ),
    ]
