# Generated by Django 5.1.15 on 2026-09-04 16:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelles', '0009_alter_signalement_options_signalement_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneEtat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type_zone', models.CharField(choices=[('foret', 'Forêt classée'), ('reserve', 'Réserve / aire protégée'), ('domaine', 'Domaine public'), ('plan_ville', 'Plan de ville'), ('autre', "Autre zone de l'État")], default='foret', max_length=20)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Zone de l'État",
                'verbose_name_plural': "Zones de l'État",
            },
        ),
    ]
